=== NickSdot/pear/dtd/rest.release.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 U (http://www.xmlspy.com) by Greg Beaver (The Chiara String Quartet) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
 <xs:element name="r">
  <xs:annotation>
   <xs:documentation>release</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="p"/>
    <xs:element ref="c"/>
    <xs:element ref="v"/>
    <xs:element ref="st"/>
    <xs:element ref="l"/>
    <xs:element ref="m"/>
    <xs:element ref="s"/>
    <xs:element ref="d"/>
    <xs:element ref="da"/>
    <xs:element ref="n"/>
    <xs:element ref="f"/>
    <xs:element ref="g"/>
    <xs:element ref="x"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name="p">
  <xs:annotation>
   <xs:documentation>package</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:simpleContent>
    <xs:extension base="xs:string">
     <xs:attribute ref="xlink:href"/>
    </xs:extension>
   </xs:simpleContent>
  </xs:complexType>
 </xs:element>
 <xs:element name="c" type="xs:string">
  <xs:annotation>
   <xs:documentation>channel</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="v" type="xs:string">
  <xs:annotation>
   <xs:documentation>version</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="st" type="xs:string">
  <xs:annotation>
   <xs:documentation>stability</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="l" type="xs:string">
  <xs:annotation>
   <xs:documentation>license</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="m" type="xs:string">
  <xs:annotation>
   <xs:documentation>releasing maintainer</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="s" type="xs:string">
  <xs:annotation>
   <xs:documentation>summary</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="d" type="xs:string">
  <xs:annotation>
   <xs:documentation>description</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="da" type="xs:string">
  <xs:annotation>
   <xs:documentation>release date</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="n" type="xs:string">
  <xs:annotation>
   <xs:documentation>release notes</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="f" type="xs:int">
  <xs:annotation>
   <xs:documentation>release size in bytes (compressed tgz)</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="g" type="xs:string">
  <xs:annotation>
   <xs:documentation>partial URI to download (no .tgz/.tar extension)</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="x" type="xs:string">
  <xs:annotation>
   <xs:documentation>link to extracted package.xml</xs:documentation>
  </xs:annotation>
 </xs:element>
</xs:schema>

=== NickSdot/pear/rest/r/http/1.3.0RC2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/http">HTTP</p>
 <c>pear.php.net</c>
 <v>1.3.0RC2</v>
 <st>beta</st>
 <l>PHP License</l>
 <m>mike</m>
 <s>Miscellaneous HTTP utilities</s>
 <d>The HTTP class is a class with static methods for doing miscellaneous
HTTP-related stuff like date formatting or language negotiation.
</d>
 <da>2004-06-30 08:42:14</da>
 <n>* Fix Bug #1748 - inproper format of date according to RFC850</n>
 <f>4299</f>
 <g>https://pear.php.net/get/HTTP-1.3.0RC2.tgz</g>
 <x xlink:href="package.1.3.0RC2.xml"/>
</r>

=== NickSdot/pear/rest/r/crypt_diffiehellman/0.2.0.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/crypt_diffiehellman">Crypt_DiffieHellman</p>
 <c>pear.php.net</c>
 <v>0.2.0</v>
 <st>beta</st>
 <l>New BSD License</l>
 <m>padraic</m>
 <s>Implementation of Diffie-Hellman Key Exchange cryptographic protocol for PHP5</s>
 <d>Implementation of the Diffie-Hellman Key Exchange cryptographic protocol
in PHP5. Enables two parties without any prior knowledge of each other
establish a secure shared secret key across an insecure channel
of communication.</d>
 <da>2007-09-29 10:34:22</da>
 <n>* Initial release!
* Updated tests location inside directory hierarchy for easier running
* Fixed a PHP variable undefined notice
* Full support for three input/output modes: Number (big integer string, Binary and Btwoc (big-endian twos complement)
* Allowed for a specific BigInteger extension to be selected for use from the Crypt_DiffieHellman contructor
* Minor typo fixes against PEAR Coding Standard</n>
 <f>10736</f>
 <g>https://pear.php.net/get/Crypt_DiffieHellman-0.2.0.tgz</g>
 <x xlink:href="package.0.2.0.xml"/>
</r>

=== NickSdot/pear/rest/r/mdb2_driver_pgsql/0.1.0.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/mdb2_driver_pgsql">MDB2_Driver_pgsql</p>
 <c>pear.php.net</c>
 <v>0.1.0</v>
 <st>beta</st>
 <l>BSD License</l>
 <m>lsmith</m>
 <s>pgsql MDB2 driver</s>
 <d>This is the PostGreSQL MDB2 driver.
 
</d>
 <da>2005-06-08 09:24:06</da>
 <n>first unbundled release from MDB2 core

- dont just check for isset() for boolean values in order to support
  setting them false as well (bug #4373)
- ensure SQL injection protection in all _quote() methods (was missing in
  some decimal, float, time, date and timestamp implementations)</n>
 <f>15498</f>
 <g>https://pear.php.net/get/MDB2_Driver_pgsql-0.1.0.tgz</g>
 <x xlink:href="package.0.1.0.xml"/>
</r>

=== NickSdot/pear/rest/r/validate_fr/0.6.0.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/validate_fr">Validate_FR</p>
 <c>pear.php.net</c>
 <v>0.6.0</v>
 <st>beta</st>
 <l>New BSD</l>
 <m>doconnor</m>
 <s>Validation class for FR</s>
 <d>Package containes locale validation for FR such as:
 * SSN
 * Postal Code
 * RIB
 * SIREN
 * SIRET
 * Region (Departements)</d>
 <da>2009-09-21 01:06:57</da>
 <n>QA release
- release in beta
- Moosh take lead
- Updated to package 2.0 (doconnor)</n>
 <f>7714</f>
 <g>https://pear.php.net/get/Validate_FR-0.6.0.tgz</g>
 <x xlink:href="package.0.6.0.xml"/>
</r>

=== NickSdot/pear/rest/r/html_template_it/1.0.0.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/html_template_it">HTML_Template_IT</p>
 <c>pear.php.net</c>
 <v>1.0.0</v>
 <st>stable</st>
 <l>PHP License</l>
 <m>pajoye</m>
 <s>Integrated Templates</s>
 <d>HTML_Template_IT:
Simple template API.
The Isotemplate API is somewhat tricky for a beginner although it is the best
one you can build. template::parse() [phplib template = Isotemplate] requests
you to name a source and a target where the current block gets parsed into.
Source and target can be block names or even handler names. This API gives you
a maximum of fexibility but you always have to know what you do which is
quite unusual for php skripter like me.

I noticed that I do not any control on which block gets parsed into which one.
If all blocks are within one file, the script knows how they are nested and in
which way you have to parse them. IT knows that inner1 is a child of block2, there's
no need to tell him about this.
Features :
  * Nested blocks
  * Include external file
  * Custom tags format (default {mytag})

HTML_Template_ITX :
With this class you get the full power of the phplib template class.
You may have one file with blocks in it but you have as well one main file
and multiple files one for each block. This is quite usefull when you have
user configurable websites. Using blocks not in the main template allows
you to modify some parts of your layout easily.
</d>
 <da>2002-09-13 01:26:00</da>
 <n>Stable release.</n>
 <f>12602</f>
 <g>https://pear.php.net/get/HTML_Template_IT-1.0.0.tgz</g>
 <x xlink:href="package.1.0.0.xml"/>
</r>

=== NickSdot/pear/rest/r/php_codesniffer/3.3.1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/php_codesniffer">PHP_CodeSniffer</p>
 <c>pear.php.net</c>
 <v>3.3.1</v>
 <st>stable</st>
 <l>BSD 3-Clause License</l>
 <m>squiz</m>
 <s>PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files to detect and fix violations of a defined set of coding standards.</s>
 <d>PHP_CodeSniffer is a set of two PHP scripts; the main phpcs script that tokenizes PHP, JavaScript and CSS files to detect violations of a defined coding standard, and a second phpcbf script to automatically correct coding standard violations. PHP_CodeSniffer is an essential development tool that ensures your code remains clean and consistent.</d>
 <da>2018-07-26 20:05:41</da>
 <n>- Support for HHVM has been dropped due to recent unfixed bugs and HHVM refocus on Hack only
  -- Thanks to Walt Sorensen and Juliette Reinders Folmer for helping to remove all HHVM exceptions from the core

- The full report (the default report) now has improved word wrapping for multi-line messages and sniff codes
  -- Thanks to Juliette Reinders Folmer for the patch
- The summary report now sorts files based on their directory location instead of just a basic string sort
  -- Thanks to Juliette Reinders Folmer for the patch
- The source report now orders error codes by name when they have the same number of errors
  -- Thanks to Juliette Reinders Folmer for the patch
- The junit report no longer generates validation errors with the Jenkins xUnit plugin
  -- Thanks to Nikolay Geo for the patch
- Generic.Commenting.DocComment no longer generates the SpacingBeforeTags error if tags are the first content in the docblock
  -- The sniff will still generate a MissingShort error if there is no short comment
  -- This allows the MissingShort error to be suppressed in a ruleset to make short descriptions optional
- Generic.Functions.FunctionCallArgumentSpacing now properly fixes multi-line function calls with leading commas
  -- Previously, newlines between function arguments would be removed
  -- Thanks to Juliette Reinders Folmer for the patch
- Generic.PHP.Syntax will now use PHP_BINARY instead of trying to discover the executable path
  -- This ensures that the sniff will always syntax check files using the PHP version that PHPCS is running under
  -- Setting the php_path config var will still override this value as normal
  -- Thanks to Willem Stuursma-Ruwen for the patch
- PSR2.Namespaces.UseDeclaration now supports commas at the end of group use declarations
  -- Also improves checking and fixing for use statements containing parse errors
  -- Thanks to Juliette Reinders Folmer for the patch
- Squiz.Arrays.ArrayDeclaration no longer removes the array opening brace while fixing
  -- This could occur when the opening brace was on a new line and the first array key directly followed
  -- This change also stops the KeyNotAligned error message being incorrectly reported in these cases
- Squiz.Arrays.ArrayDeclaration no longer tries to change multi-line arrays to single line when they contain comments
  -- Fixes a conflict between this sniff and some indentation sniffs
- Squiz.Classes.ClassDeclaration no longer enforces spacing rules when a class is followed by a function
  -- Fixes a conflict between this sniff and the Squiz.WhiteSpace.FunctionSpacing sniff
- The Squiz.Classes.ValidClassName.NotCamelCaps message now references PascalCase instead of CamelCase
  -- The &quot;CamelCase class name&quot; metric produced by the sniff has been changed to &quot;PascalCase class name&quot;
  -- This reflects the fact that the class name check is actually a Pascal Case check and not really Camel Case
  -- Thanks to Tom H Anderson for the patch
- Squiz.Commenting.InlineComment no longer enforces spacing rules when an inline comment is followed by a docblock
  -- Fixes a conflict between this sniff and the Squiz.WhiteSpace.FunctionSpacing sniff
- Squiz.WhiteSpace.OperatorSpacing no longer tries to fix operator spacing if the next content is a comment on a new line
  -- Fixes a conflict between this sniff and the Squiz.Commenting.PostStatementComment sniff
  -- Also stops PHPCS annotations from being moved to a different line, potentially changing their meaning
  -- Thanks to Juliette Reinders Folmer for the patch
- Squiz.WhiteSpace.FunctionSpacing no longer checks spacing of functions at the top of an embedded PHP block
  -- Fixes a conflict between this sniff and the Squiz.PHP.EmbeddedPHP sniff
  -- Thanks to Juliette Reinders Folmer for the patch
- Squiz.WhiteSpace.MemberVarSpacing no longer checks spacing before member vars that come directly after methods
  -- Fixes a conflict between this sniff and the Squiz.WhiteSpace.FunctionSpacing sniff
- Squiz.WhiteSpace.SuperfluousWhitespace now recognizes unicode whitespace at the start and end of a file
  -- Thanks to Juliette Reinders Folmer for the patch
- Fixed bug #2029 : Squiz.Scope.MemberVarScope throws fatal error when a property is found in an interface
  -- Thanks to Juliette Reinders Folmer for the patch
- Fixed bug #2047 : PSR12.Classes.ClassInstantiation false positive when instantiating class from array index
- Fixed bug #2048 : GenericFormatting.MultipleStatementAlignment false positive when assigning values inside an array
- Fixed bug #2053 : PSR12.Classes.ClassInstantiation incorrectly fix when using member vars and some variable formats
- Fixed bug #2065 : Generic.ControlStructures.InlineControlStructure fixing fails when inline control structure contains closure
- Fixed bug #2072 : Squiz.Arrays.ArrayDeclaration throws NoComma error when array value is a shorthand IF statement
- Fixed bug #2082 : File with &quot;defined() or define()&quot; syntax triggers PSR1.Files.SideEffects.FoundWithSymbols
- Fixed bug #2095 : PSR2.Namespaces.NamespaceDeclaration does not handle namespaces defined over multiple lines</n>
 <f>595329</f>
 <g>https://pear.php.net/get/PHP_CodeSniffer-3.3.1.tgz</g>
 <x xlink:href="package.3.3.1.xml"/>
</r>

=== NickSdot/pear/rest/r/codegen_mysql_udf/1.0.0RC1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/codegen_mysql_udf">CodeGen_MySQL_UDF</p>
 <c>pear.php.net</c>
 <v>1.0.0RC1</v>
 <st>beta</st>
 <l>PHP</l>
 <m>hholzgra</m>
 <s>Tool to generate MySQL UDF extensions from an XML description</s>
 <d>CodeGen_MySQL_UDF is a code generator for MySQL User Defined Function (UDF)
extensions similar to PECL_Gen for PHP. 
It reads in configuration options, function prototypes and code fragments
from an XML description file and generates a complete ready-to-compile
UDF extension.
Preliminary documentation can be found here:
http://talks.php.net/show/UDF_Gen</d>
 <da>2009-02-11 09:14:37</da>
 <n>First release candidate ...

changes since 0.9.8:
- removed plugin_dir detection magic as it can never be reliable
  specifying the right --libdir is now back in the developers field
- added &quot;html&quot; and &quot;pdf&quot; make targets
- rely on &quot;autreconf&quot; instead of running autotools one by one
- support of &lt;group&gt; tags and conditional compilation
- now generating variables for parameter attributes
- udf-gen script now works on windows, too
- Windows related code generation fixes
- generating .def file for Windows builds now
- &lt;udf&gt; is now an alias of &lt;extension&gt;</n>
 <f>25518</f>
 <g>https://pear.php.net/get/CodeGen_MySQL_UDF-1.0.0RC1.tgz</g>
 <x xlink:href="package.1.0.0RC1.xml"/>
</r>

=== NickSdot/pear/rest/r/xml_xpath/1.2.3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/xml_xpath">XML_XPath</p>
 <c>pear.php.net</c>
 <v>1.2.3</v>
 <st>stable</st>
 <l>PHP License</l>
 <m>arnaud</m>
 <s>The PEAR::XML_XPath class provided an XPath/DOM XML manipulation, maneuvering and query interface.</s>
 <d>The PEAR::XML_XPath class provided an XPath/DOM XML manipulation, maneuvering and 
query interface.
The class allows for easy manipulation, maneuvering and querying of a domxml tree using
both xpath queries and DOM walk functions.  It uses an internal pointer for all
methods on which the action is performed.  Results from an dom/xpath query are returned
as an XPath_Result object, which contains an internal array of DOM nodes and which extends 
the common DOM class and hence contains all the DOM functions from the main object to run
on each of the elements in the internal array.  This class tries to hold as close as possible       to the DOM Recommendation.  You MUST have the domxml extension to use this class.
The XML_XPath class was inspired by a class maintained by Nigel Swinson called phpxpath.
The phpxpath class does not rely on PHP xmldom functions and is therefore a sibling to
this class: http://sourceforge.net/projects/phpxpath
 
</d>
 <da>2005-10-18 01:25:39</da>
 <n>There is now a dependency on PHP4 since PHP5 has out-of-the-box for XPath in both DOM and SimpleXML.</n>
 <f>19179</f>
 <g>https://pear.php.net/get/XML_XPath-1.2.3.tgz</g>
 <x xlink:href="package.1.2.3.xml"/>
</r>
