=== NickSdot/pear/dtd/rest.release.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 U (http://www.xmlspy.com) by Greg Beaver (The Chiara String Quartet) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
 <xs:element name="r">
  <xs:annotation>
   <xs:documentation>release</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="p"/>
    <xs:element ref="c"/>
    <xs:element ref="v"/>
    <xs:element ref="st"/>
    <xs:element ref="l"/>
    <xs:element ref="m"/>
    <xs:element ref="s"/>
    <xs:element ref="d"/>
    <xs:element ref="da"/>
    <xs:element ref="n"/>
    <xs:element ref="f"/>
    <xs:element ref="g"/>
    <xs:element ref="x"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name="p">
  <xs:annotation>
   <xs:documentation>package</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:simpleContent>
    <xs:extension base="xs:string">
     <xs:attribute ref="xlink:href"/>
    </xs:extension>
   </xs:simpleContent>
  </xs:complexType>
 </xs:element>
 <xs:element name="c" type="xs:string">
  <xs:annotation>
   <xs:documentation>channel</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="v" type="xs:string">
  <xs:annotation>
   <xs:documentation>version</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="st" type="xs:string">
  <xs:annotation>
   <xs:documentation>stability</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="l" type="xs:string">
  <xs:annotation>
   <xs:documentation>license</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="m" type="xs:string">
  <xs:annotation>
   <xs:documentation>releasing maintainer</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="s" type="xs:string">
  <xs:annotation>
   <xs:documentation>summary</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="d" type="xs:string">
  <xs:annotation>
   <xs:documentation>description</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="da" type="xs:string">
  <xs:annotation>
   <xs:documentation>release date</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="n" type="xs:string">
  <xs:annotation>
   <xs:documentation>release notes</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="f" type="xs:int">
  <xs:annotation>
   <xs:documentation>release size in bytes (compressed tgz)</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="g" type="xs:string">
  <xs:annotation>
   <xs:documentation>partial URI to download (no .tgz/.tar extension)</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="x" type="xs:string">
  <xs:annotation>
   <xs:documentation>link to extracted package.xml</xs:documentation>
  </xs:annotation>
 </xs:element>
</xs:schema>

=== NickSdot/pear/rest/r/html_progress2/2.1.1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/html_progress2">HTML_Progress2</p>
 <c>pear.php.net</c>
 <v>2.1.1</v>
 <st>stable</st>
 <l>PHP License 3.01</l>
 <m>farell</m>
 <s>How to include a loading bar in your XHTML documents quickly and easily.</s>
 <d>This package provides a way to add a loading bar fully customizable in existing XHTML documents.
Your browser should accept DHTML feature.

Features:
- create horizontal, vertival bar and also circle, ellipse and polygons (square, rectangle).
- allows usage of existing external StyleSheet and/or JavaScript.
- all elements (progress, cells, labels) are customizable by their html properties.
- percent/labels are floating all around the progress meter.
- compliant with all CSS/XHMTL standards.
- integration with all template engines is very easy.
- implements Observer design pattern. It is possible to add Listeners.
- adds a customizable monitor pattern to display a progress bar.
  User-end can abort progress at any time.
- allows many progress meter on same page without uses of iframe solution.
- error handling system that support native PEAR_Error, but also PEAR_ErrorStack, and
  any other system you might want to plug-in.
- PHP 5 ready.</d>
 <da>2006-12-22 12:06:34</da>
 <n>* bugs
- fixed bug #8684 : Problem with generated JavaScript
- fixed &quot;examples/generatorcus.php&quot; to use new architecture with external stylesheet introduced on August 11, 2006.

* news (improved code)
- used now &quot;className&quot; property rather than &quot;visibility&quot;
and reduced div tags count used to build a progress bar (only 10 rather than 20 )
- apply more CS (space code indent, ...)
- add &quot;alt&quot; attribute to img html-tag to be more xhtml compliant
- JS function &quot;hideProgress&quot; lose its second parameter (no more needed)</n>
 <f>368598</f>
 <g>https://pear.php.net/get/HTML_Progress2-2.1.1.tgz</g>
 <x xlink:href="package.2.1.1.xml"/>
</r>

=== NickSdot/pear/rest/r/log/1.8.4.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/log">Log</p>
 <c>pear.php.net</c>
 <v>1.8.4</v>
 <st>stable</st>
 <l>PHP License</l>
 <m>jon</m>
 <s>Logging utilities</s>
 <d>The Log framework provides an abstracted logging system.  It supports logging to console, file, syslog, SQL, Sqlite, mail and mcal targets.  It also provides a subject - observer mechanism.
</d>
 <da>2004-02-17 00:31:24</da>
 <n>The Log package now requires PHP 4.3.0 or later.

If an object or array is passed as a log event, its human-readable representation will be used.

It's now possible to specify the default priority for events logged using the log() method.</n>
 <f>29453</f>
 <g>https://pear.php.net/get/Log-1.8.4.tgz</g>
 <x xlink:href="package.1.8.4.xml"/>
</r>

=== NickSdot/pear/rest/r/mail_mime/1.8.7.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/mail_mime">Mail_Mime</p>
 <c>pear.php.net</c>
 <v>1.8.7</v>
 <st>stable</st>
 <l>BSD Style</l>
 <m>alec</m>
 <s>Mail_Mime provides classes to create MIME messages.</s>
 <d>Mail_Mime provides classes to deal with the creation and manipulation of MIME messages.
It allows people to create e-mail messages consisting of:
* Text Parts
* HTML Parts
* Inline HTML Images
* Attachments
* Attached messages

It supports big messages, base64 and quoted-printable encodings and
non-ASCII characters in filenames, subjects, recipients, etc. encoded
using RFC2047 and/or RFC2231.</d>
 <da>2012-12-25 17:28:19</da>
 <n>* Bug #5333: Fix more return by reference errors [alec]
* Bug #19754: Fix compatibility with PHP4 [alec]</n>
 <f>31837</f>
 <g>https://pear.php.net/get/Mail_Mime-1.8.7.tgz</g>
 <x xlink:href="package.1.8.7.xml"/>
</r>

=== NickSdot/pear/rest/r/php_docblockgenerator/1.0.0RC1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/php_docblockgenerator">PHP_DocBlockGenerator</p>
 <c>pear.php.net</c>
 <v>1.0.0RC1</v>
 <st>beta</st>
 <l>The BSD License</l>
 <m>mcorne</m>
 <s>DocBlock Generator</s>
 <d>Creates the file Page block and the DocBlocks for includes, global variables, functions, parameters, classes, constants, properties and methods.
Accepts parameters to set the category name, the package name, the author's name and email, the license, the package link, etc...
Attempts to guess variable and parameters types.
Aligns the DocBlock tags.
Tags are not updated or added to existing DocBlocks but only realigned.
The package can be run by: calling the &quot;PHP_DocBlockGenerator&quot; class, or by running the &quot;docblockgen&quot; DOS/Unix command.
Fully tested with phpUnit. Code coverage test close to 100%.</d>
 <da>2007-06-29 15:56:29</da>
 <n>* Initial PEAR release
* Testing with PHPUnit
* Using PHPCompat to determine the PHP version
* Using Consol_Getopt for the CLI
* Various fixes and enhancements</n>
 <f>41407</f>
 <g>https://pear.php.net/get/PHP_DocBlockGenerator-1.0.0RC1.tgz</g>
 <x xlink:href="package.1.0.0RC1.xml"/>
</r>

=== NickSdot/pear/rest/r/image_puzzle/0.2.1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/image_puzzle">Image_Puzzle</p>
 <c>pear.php.net</c>
 <v>0.2.1</v>
 <st>beta</st>
 <l>PHP License</l>
 <m>fela</m>
 <s>Generates puzzle pieces from image file</s>
 <d>PEAR::Image_Puzzle divides an image to puzzle pieces.



* Provides a few edge styles to generate puzzle pieces

* Allow saving each piece to separate files

* Allow getting information about each piece coordinates accoring to original image
 
</d>
 <da>2006-04-29 01:50:02</da>
 <n>- changed saving files to proper file type according to given extension

			    - checking if type supports transparent colour

			    - fixed saving gif by limiting number of coulour to 256</n>
 <f>7467</f>
 <g>https://pear.php.net/get/Image_Puzzle-0.2.1.tgz</g>
 <x xlink:href="package.0.2.1.xml"/>
</r>

=== NickSdot/pear/rest/r/net_ipv6/1.1.0b1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/net_ipv6">Net_IPv6</p>
 <c>pear.php.net</c>
 <v>1.1.0b1</v>
 <st>beta</st>
 <l>BSD</l>
 <m>alexmerz</m>
 <s>Check and validate IPv6 addresses</s>
 <d>The class allows you to:
* check if an address is an IPv6 address
* compress/uncompress IPv6 addresses
* check for an IPv4 compatible ending in an IPv6 address
* check the assigned address space of an IPv6 address
* do netmask calculations</d>
 <da>2008-10-27 21:09:19</da>
 <n>Because this release adds a new method and some bug tickets are still open, the package
release is named as Beta, instead of releasing a 5th RC version.

#14728   add parseAddress(), thanks to Nicholas Williams!
#14767   most CS issues should be solved</n>
 <f>6240</f>
 <g>https://pear.php.net/get/Net_IPv6-1.1.0b1.tgz</g>
 <x xlink:href="package.1.1.0b1.xml"/>
</r>

=== NickSdot/pear/rest/r/validate/0.7.0.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/validate">Validate</p>
 <c>pear.php.net</c>
 <v>0.7.0</v>
 <st>beta</st>
 <l>New BSD</l>
 <m>amir</m>
 <s>Validation class</s>
 <d>Package to validate various datas. It includes :
    - numbers (min/max, decimal or not)
    - email (syntax, domain check, rfc822)
    - string (predifined type alpha upper and/or lowercase, numeric,...)
    - date (min, max, rfc822 compliant)
    - uri (RFC2396)
    - possibility valid multiple data with a single method call (::multiple)</d>
 <da>2006-11-17 11:51:12</da>
 <n>- string():
 * New chars in VALIDATE_EALPHA_LOWER and UPPER
- date():
 * RFC822 date-time format compliant</n>
 <f>16841</f>
 <g>https://pear.php.net/get/Validate-0.7.0.tgz</g>
 <x xlink:href="package.0.7.0.xml"/>
</r>

=== NickSdot/pear/rest/r/mdb2_driver_oci8/0.2.1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/mdb2_driver_oci8">MDB2_Driver_oci8</p>
 <c>pear.php.net</c>
 <v>0.2.1</v>
 <st>alpha</st>
 <l>BSD License</l>
 <m>lsmith</m>
 <s>oci8 MDB2 driver</s>
 <d>This is the Oracle OCI8 MDB2 driver.
 
</d>
 <da>2005-12-28 05:25:21</da>
 <n>- fixed typo in _execute() that would lead to using the wrong types inside the result object
- fixed typo in _execute() that lead to using the wrong ressource inside the result object
- various fixes for alterTable()
- fixed testNow()

open todo items:
- handle autoincremement fields in alterTable()
- there are still a number of missing methods in the reverse and datatype module
- there are still severe stability issues due to ext/oci8, especially on windows
- ensure that all primary/unique/foreign key handling is only in the contraint methods</n>
 <f>18358</f>
 <g>https://pear.php.net/get/MDB2_Driver_oci8-0.2.1.tgz</g>
 <x xlink:href="package.0.2.1.xml"/>
</r>
