=== NickSdot/pear/dtd/rest.release.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 U (http://www.xmlspy.com) by Greg Beaver (The Chiara String Quartet) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
 <xs:element name="r">
  <xs:annotation>
   <xs:documentation>release</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="p"/>
    <xs:element ref="c"/>
    <xs:element ref="v"/>
    <xs:element ref="st"/>
    <xs:element ref="l"/>
    <xs:element ref="m"/>
    <xs:element ref="s"/>
    <xs:element ref="d"/>
    <xs:element ref="da"/>
    <xs:element ref="n"/>
    <xs:element ref="f"/>
    <xs:element ref="g"/>
    <xs:element ref="x"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 <xs:element name="p">
  <xs:annotation>
   <xs:documentation>package</xs:documentation>
  </xs:annotation>
  <xs:complexType>
   <xs:simpleContent>
    <xs:extension base="xs:string">
     <xs:attribute ref="xlink:href"/>
    </xs:extension>
   </xs:simpleContent>
  </xs:complexType>
 </xs:element>
 <xs:element name="c" type="xs:string">
  <xs:annotation>
   <xs:documentation>channel</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="v" type="xs:string">
  <xs:annotation>
   <xs:documentation>version</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="st" type="xs:string">
  <xs:annotation>
   <xs:documentation>stability</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="l" type="xs:string">
  <xs:annotation>
   <xs:documentation>license</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="m" type="xs:string">
  <xs:annotation>
   <xs:documentation>releasing maintainer</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="s" type="xs:string">
  <xs:annotation>
   <xs:documentation>summary</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="d" type="xs:string">
  <xs:annotation>
   <xs:documentation>description</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="da" type="xs:string">
  <xs:annotation>
   <xs:documentation>release date</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="n" type="xs:string">
  <xs:annotation>
   <xs:documentation>release notes</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="f" type="xs:int">
  <xs:annotation>
   <xs:documentation>release size in bytes (compressed tgz)</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="g" type="xs:string">
  <xs:annotation>
   <xs:documentation>partial URI to download (no .tgz/.tar extension)</xs:documentation>
  </xs:annotation>
 </xs:element>
 <xs:element name="x" type="xs:string">
  <xs:annotation>
   <xs:documentation>link to extracted package.xml</xs:documentation>
  </xs:annotation>
 </xs:element>
</xs:schema>

=== NickSdot/pear/rest/r/pearweb_gopear/1.1.4.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/pearweb_gopear">pearweb_gopear</p>
 <c>pear.php.net</c>
 <v>1.1.4</v>
 <st>stable</st>
 <l>PHP License</l>
 <m>cweiske</m>
 <s>go-pear script for pear.php.net</s>
 <d>go-pear is the online PEAR installer: just download it and run it (through a browser or command line), it will set up a minimal PEAR installation that will be ready for immediatel use.

You can download go-pear from http://pear.php.net/go-pear
(this is merely the pearweb package hosting it)</d>
 <da>2009-09-07 22:33:39</da>
 <n>- text/javascript for all &lt;script&gt; [clockwerx]
- Fix bug #12910 - &lt;br&gt; begone! [clockwerx]</n>
 <f>24646</f>
 <g>https://pear.php.net/get/pearweb_gopear-1.1.4.tgz</g>
 <x xlink:href="package.1.1.4.xml"/>
</r>

=== NickSdot/pear/rest/r/pear_info/1.7.0RC3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/pear_info">PEAR_Info</p>
 <c>pear.php.net</c>
 <v>1.7.0RC3</v>
 <st>beta</st>
 <l>PHP License</l>
 <m>farell</m>
 <s>Show Information about your PEAR install and its packages</s>
 <d>This package generates a comprehensive information page for your current PEAR install.
* The format for the page is similar to that for phpinfo() except using PEAR colors.
* Has complete PEAR Credits (based on the packages you have installed).
* Will show if there is a newer version than the one presently installed (and what its state is)
* Each package has an anchor in the form pkg_PackageName - where PackageName is a case-sensitive PEAR package name</d>
 <da>2007-07-10 14:03:25</da>
 <n>* changes
- Credits page is now customizable with PEAR_INFO_CREDITS_* constant
- You may have a standalone html page (default behavior) with PEAR_INFO_FULLPAGE
  or just part of html code related to information wanted ; Easy to include in your own pages
- new method that give PEAR members list (president, group, docs, website)

Stable release 1.7.0 is scheduled for July 17. This is the last release candidate.</n>
 <f>20924</f>
 <g>https://pear.php.net/get/PEAR_Info-1.7.0RC3.tgz</g>
 <x xlink:href="package.1.7.0RC3.xml"/>
</r>

=== NickSdot/pear/rest/r/mdb2/2.0.0RC2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/mdb2">MDB2</p>
 <c>pear.php.net</c>
 <v>2.0.0RC2</v>
 <st>beta</st>
 <l>BSD License</l>
 <m>lsmith</m>
 <s>database abstraction layer</s>
 <d>PEAR MDB2 is a merge of the PEAR DB and Metabase php database abstraction layers.

Note that the API will be adapted to better fit with the new php5 only PDO
before the first stable release.

It provides a common API for all supported RDBMS. The main difference to most
other DB abstraction packages is that MDB2 goes much further to ensure
portability. Among other things MDB2 features:
* An OO-style query API
* A DSN (data source name) or array format for specifying database servers
* Datatype abstraction and on demand datatype conversion
* Various optional fetch modes to fix portability issues
* Portable error codes
* Sequential and non sequential row fetching as well as bulk fetching
* Ability to make buffered and unbuffered queries
* Ordered array and associative array for the fetched rows
* Prepare/execute (bind) emulation
* Sequence emulation
* Replace emulation
* Limited sub select emulation
* Row limit support
* Transactions support
* Large Object support
* Index/Unique Key/Primary Key support
* Autoincrement emulation
* Module framework to load advanced functionality on demand
* Ability to read the information schema
* RDBMS management methods (creating, dropping, altering)
* Reverse engineering schemas from an existing DB
* SQL function call abstraction
* Full integration into the PEAR Framework
* PHPDoc API documentation
 
</d>
 <da>2005-12-28 05:22:33</da>
 <n>- fixed testNow() to use the datatype abstraction
- fixed testGetTableFieldDefinition() to use a blob column instead of a clob
  since we default to blob when we cannot differntiate between blob and clob
- split up alterTable() testing into two separate test methods
- removed errorNative() was never implemented, use errorInfo() instead
- fixed major bug in _fixResultArrayValues() that would lead to performance or
  incorrect application of portability features
- phpdoc fixes in LOB.php, Iterator.php, Date.php and Extended.php
- removed not required prev() and hasPrev() from the SeekableIterator implementation</n>
 <f>90674</f>
 <g>https://pear.php.net/get/MDB2-2.0.0RC2.tgz</g>
 <x xlink:href="package.2.0.0RC2.xml"/>
</r>

=== NickSdot/pear/rest/r/http_request2/2.6.0.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/http_request2">HTTP_Request2</p>
 <c>pear.php.net</c>
 <v>2.6.0</v>
 <st>stable</st>
 <l>BSD 3-Clause License</l>
 <m>avb</m>
 <s>Provides an easy way to perform HTTP requests.</s>
 <d>PHP5 rewrite of HTTP_Request package (with parts of HTTP_Client). Provides
cleaner API and pluggable Adapters:
  * Socket adapter, based on old HTTP_Request code,
  * Curl adapter, wraps around PHP's cURL extension,
  * Mock adapter, to use for testing packages dependent on HTTP_Request2.
Supports POST requests with data and file uploads, basic and digest
authentication, cookies, managing cookies across requests, proxies, gzip and
deflate encodings, redirects, monitoring the request progress with Observers...</d>
 <da>2023-11-01 16:04:51</da>
 <n>* Tested on PHP 8.2 and 8.3
* Use psalm for static analysis, several minor issues fixed
* Correctly parse HTTP status line with an empty reason-phrase
  (see https://github.com/pear/HTTP_Request2/pull/26)
* Updated Public Suffix List</n>
 <f>127945</f>
 <g>https://pear.php.net/get/HTTP_Request2-2.6.0.tgz</g>
 <x xlink:href="package.2.6.0.xml"/>
</r>

=== NickSdot/pear/rest/r/image_graph/0.7.2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/image_graph">Image_Graph</p>
 <c>pear.php.net</c>
 <v>0.7.2</v>
 <st>alpha</st>
 <l>LGPL</l>
 <m>nosey</m>
 <s>A package for displaying (numerical) data as a graph/chart/plot.</s>
 <d>Image_Graph provides a set of classes that creates graphs/plots/charts based on (numerical) data.

Many different plot types are supported: Bar, line, area, step, impulse, scatter, radar, pie, map, candlestick, band, box &amp; whisker and smoothed line, area and radar plots.

The graph is highly customizable, making it possible to get the exact look and feel that is required.

The output is controlled by a Image_Canvas, which facilitates easy output to many different output formats, amongst others, GD (PNG, JPEG, GIF, WBMP), PDF (using PDFLib), Scalable Vector Graphics (SVG).

Image_Graph is compatible with both PHP4 and PHP5.
 
</d>
 <da>2006-03-02 07:42:17</da>
 <n>* Added Pie chart support for grouping items with values below a specified threshold in a &quot;the rest&quot; group
* Added possibility to set color of axis ticks (thanks to bdondo from forum)
* Added clipping support, causing forceMinimum() and forceMaximum() to show expected results
* Modified axis arrows, so that an axis with all negative values, the arrow will be shown at the minimum value instead of maximum
* Fixed a bug with Image_Graph_DataPreprocessor_Function not working, when callback function is an object method
* Fixed a bug with Candlestick, Band and Box &amp; Whisker plots not working when using markers
* Fixed Bug #6024 &quot;Undefined variable: parameters&quot;
* Fixed Bug #6085 &quot;Graph doesn't understand a numeric variable extracted from the GET method.&quot;
* Fixed Bug #6919 &quot;Isolated points in linegraphs with breaks drawn incorrectly&quot;
* Fixed Bug #6921 &quot;Marker not drawn for points with Y value == 0&quot;
* Fixed Bug #6941 &quot;Logarithmic axis values between 0 and 1&quot;
* Fixed Request #5985 &quot;Logarithmic Axis Minimum Value&quot;
* Fixed a problem with labels not appearing on the same baseline
* Added possibility to specify padding on all edges of an element separately
* Updated some API documentation entries</n>
 <f>368056</f>
 <g>https://pear.php.net/get/Image_Graph-0.7.2.tgz</g>
 <x xlink:href="package.0.7.2.xml"/>
</r>

=== NickSdot/pear/rest/r/html_table/1.1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/html_table">HTML_Table</p>
 <c>pear.php.net</c>
 <v>1.1</v>
 <st>stable</st>
 <l>PHP License</l>
 <m>mansion</m>
 <s>PEAR::HTML_Table makes the design of HTML tables easy, flexible, reusable and efficient.</s>
 <d>The PEAR::HTML_Table package provides methods for easy and efficient design of HTML tables.
* Lots of customization options.
* Tables can be modified at any time.
* The logic is the same as standard HTML editors.
* Handles col and rowspans. 
* PHP code is shorter, easier to read and to maintain.
* Tables options can be reused.
</d>
 <da>2002-07-21 18:44:00</da>
 <n>Added new most-wanted features:
* Accept TR tags attributes
* Accept alternatives for cell attributes in rows and columns
* Can get cell attributes
* Can get row attributes
* RaiseError fixes.</n>
 <f>5168</f>
 <g>https://pear.php.net/get/HTML_Table-1.1.tgz</g>
 <x xlink:href="package.1.1.xml"/>
</r>

=== NickSdot/pear/rest/r/structures_datagrid_renderer_xul/0.1.2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/structures_datagrid_renderer_xul">Structures_DataGrid_Renderer_XUL</p>
 <c>pear.php.net</c>
 <v>0.1.2</v>
 <st>beta</st>
 <l>New BSD</l>
 <m>wiesemann</m>
 <s>Renderer driver that generates the XML string for a XUL listbox</s>
 <d>This is a Renderer driver for Structures_DataGrid that generates the XML
string for a XUL listbox.</d>
 <da>2006-12-16 11:13:18</da>
 <n>- Bug #9548: added support for per-column default sort directions
  (thanks to Anton, hire at ukr dot net)
- this package is now licensed under the New BSD license</n>
 <f>3974</f>
 <g>https://pear.php.net/get/Structures_DataGrid_Renderer_XUL-0.1.2.tgz</g>
 <x xlink:href="package.0.1.2.xml"/>
</r>

=== NickSdot/pear/rest/r/services_trackback/0.6.2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<r xmlns="http://pear.php.net/dtd/rest.release"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xsi:schemaLocation="http://pear.php.net/dtd/rest.release
    https://pear.php.net/dtd/rest.release.xsd">
 <p xlink:href="/rest/p/services_trackback">Services_Trackback</p>
 <c>pear.php.net</c>
 <v>0.6.2</v>
 <st>beta</st>
 <l>PHP License</l>
 <m>doconnor</m>
 <s>Trackback - A generic class for sending and receiving trackbacks.</s>
 <d>A generic class for sending and receiving trackbacks.</d>
 <da>2008-10-01 10:19:42</da>
 <n>Fixes for Bug #13456 and Bug #13457 - reset() was not functional for two drivers.
Implemented a Mock SpamCheck driver for ease of unit testing
Upgraded to work with PHPUnit 3
PHPCS improvements</n>
 <f>20003</f>
 <g>https://pear.php.net/get/Services_Trackback-0.6.2.tgz</g>
 <x xlink:href="package.0.6.2.xml"/>
</r>
